Adopter.destroy_all
Dog.destroy_all
Shelter.destroy_all


barkr = Shelter.create(name: "Barkr", location: "Staten Island", kill_shelter: true)
dog_depot = Shelter.create(name: "The Dog Depot", location: "Staten Island", kill_shelter: true)
rock_howl = Shelter.create(name: "Rock and Howl", location: "Staten Island", kill_shelter: true)
 bob_barker = Shelter.create(name: "Bobs Barkers", location: "Staten Island", kill_shelter: false)
dogs_r_us = Shelter.create(name: "Dogs R Us", location: "Brooklyn", kill_shelter: false )
 super_pups = Shelter.create(name: "Super Pups", location: "Brooklyn", kill_shelter: false)
dog_mart = Shelter.create(name: "Dog-Mart", location: "Brooklyn", kill_shelter: false )
dogs_dogs_dogs = Shelter.create(name:"Dogs Dogs Dogs", location:"Queens", kill_shelter: false)
paw_club = Shelter.create(name:"Paw Club", location:"Queens", kill_shelter: false)
roofus = Shelter.create(name:"Roofus and Friends", location:"Queens", kill_shelter: true)
dogs_tail = Shelter.create(name:"Adoptions: a dog's tail", location:"Bronx", kill_shelter: false)
ayo = Shelter.create(name:"Ayo, I got dogs ova here", location:"Bronx", kill_shelter: false)
dog_king = Shelter.create(name:"Dog King", location:"Bronx", kill_shelter: false)
dogs_genie = Shelter.create(name:"Dog Genie", location:"Manhattan", kill_shelter: false)
lower_east_dogs = Shelter.create(name:"Lower East Dogs", location:"Manhattan", kill_shelter: false)
uptown_dogs = Shelter.create(name:"Uptown Dogs", location:"Manhattan", kill_shelter: false)




scoobs = Dog.create(name: "Scooby Doo", age: 7, size: "Large", personality: "Calm", breed: "Great Dane", shelter_id: barkr.id, sex: "male")
clifford = Dog.create(name: "Clifford", age: 5, size: "Large", personality: "Active", breed: "Big Red Dog", shelter_id: dogs_r_us.id, sex: "female")
air_bud = Dog.create(name: "Air Bud", age: 3, size: "Large", personality: "Active", breed: "Golden Retriever", shelter_id: dogs_r_us.id, sex: "male")
ginger = Dog.create(name: "Ginger", age: 4, size: "Large", personality: "Active", breed: "German Shepherd", shelter_id: dogs_dogs_dogs.id, sex: "male")
gizmo = Dog.create(name: "Gizmo", age: 5, size: "Small", personality: "Active", breed: "Morkie", shelter_id: dogs_dogs_dogs.id, sex: "female")
lucky = Dog.create(name: "Lucky", age: 5, size: "Small", personality: "Calm", breed: "Morkie", shelter_id: roofus.id, sex: "female")
peanut = Dog.create(name: "Peanut", age: 4, size: "Large", personality: "Active", breed: "German Shepherd", shelter_id: roofus.id, sex: "male")
howling = Dog.create(name: "J.K. Howling", age: 3, size: "Medium", personality: "Calm", breed: "Basset Hound", shelter_id: barkr.id, sex: "male")
magnum = Dog.create(name: "Magnum", age: 6, size: "Large", personality: "Calm", breed: "Bernese Mountain Dog", shelter_id: barkr.id, sex: "female")
amadeus = Dog.create(name: "Amadeus", age: 4, size: "Large", personality: "Calm", breed: "Great Dane", shelter_id: dog_king.id, sex: "female")
niinja = Dog.create(name: "Niinja", age: 2, size: "Large", personality: "Active", breed: "German Shepherd", shelter_id: lower_east_dogs.id, sex: "female")
hanka = Dog.create(name: "Hanka", age: 5, size: "Small", personality: "Active", breed: "Bichon Frise", shelter_id: dogs_genie.id, sex: "male")
indi = Dog.create(name: "Indi", age: 3, size: "Large", personality: "Calm", breed: "Great Dane", shelter_id: dog_depot.id, sex: "female")
sam = Dog.create(name: "Sam", age: 2, size: "Medium", personality: "Calm", breed: "Basset Hound", shelter_id: rock_howl.id, sex: "male")
alfredo = Dog.create(name: "Alfredo", age: 6, size: "Small", personality: "Active", breed: "Maltese", shelter_id: lower_east_dogs.id, sex: "male")
patches = Dog.create(name: "Patches", age: 7, size: "Small", personality: "Active", breed: "Shih Tzu", shelter_id: dog_king.id, sex: "female")
waffles = Dog.create(name: "Waffles", age: 3, size: "small", personality: "Calm", breed: "Yorkshire Terrier", shelter_id: rock_howl.id, sex: "female")
peaches = Dog.create(name: "Peaches", age: 4, size: "Medium", personality: "Calm", breed: "Basset Hound", shelter_id: bob_barker.id, sex: "male")
janus = Dog.create(name: "Janus", age: 6, size: "Small", personality: "Active", breed: "Maltese", shelter_id: dogs_genie.id, sex: "female")
yandi = Dog.create(name: "Yandi", age: 4, size: "Small", personality: "Active", breed: "Boston Terrier", shelter_id: barkr.id, sex: "female")
wallace = Dog.create(name: "Wallace", age: 3, size: "Small", personality: "Active", breed: "Boston Terrier", shelter_id: bob_barker.id, sex: "male")
usher = Dog.create(name: "Usher", age: 2, size: "Medium", personality: "Calm", breed: "Bordie Collie", shelter_id: dog_depot.id, sex: "male")
nettie = Dog.create(name: "Nettie Spaghetti", age: 1, size: "Medium", personality: "Active", breed: "Corgi", shelter_id: super_pups.id, sex: "female")
quill = Dog.create(name: "Quill", age: 5, size: "Large", personality: "Calm", breed: "Great Dane", shelter_id: super_pups.id, sex: "male")
kapone = Dog.create(name: "Kapone", age: 7, size: "Medium", personality: "Calm", breed: "Bulldog", shelter_id: dog_mart.id, sex: "male")
paxton = Dog.create(name: "Paxton", age: 5, size: "Medium", personality: "Calm", breed: "Corgi", shelter_id: dog_mart.id, sex: "female")
iris = Dog.create(name: "Iris", age: 4, size: "Large", personality: "Active", breed: "Husky", shelter_id: paw_club.id, sex: "male")
lee = Dog.create(name: "Lee", age: 3, size: "Small", personality: "Calm", breed: "Yorkshire Terrier", shelter_id: paw_club.id, sex: "female")
pico = Dog.create(name: "Pico", age: 3, size: "Large", personality: "Active", breed: "Golden Retriever", shelter_id: dogs_tail.id, sex: "male")
quin = Dog.create(name: "Quin", age: 3, size: "Large", personality: "Active", breed: "Husky", shelter_id: dogs_tail.id, sex: "male")
terry = Dog.create(name: "Terry", age: 3, size: "Small", personality: "Active", breed: "Boston Terrier", shelter_id: ayo.id, sex: "male")
bob = Dog.create(name: "Bob", age: 3, size: "Small", personality: "Calm", breed: "Boston Terrier", shelter_id: ayo.id, sex: "female")
fry = Dog.create(name: "Fry", age: 3, size: "Small", personality: "Active", breed: "Bichon Frise", shelter_id: uptown_dogs.id, sex: "male")
zeek = Dog.create(name: "Zeek", age: 2, size: "Small", personality: "calm", breed: "Yorkshire Terry", shelter_id: uptown_dogs.id, sex: "male")
